name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cd src && make && cd ..
      - name: Test
        run: ./loda test
  build-macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cd src && make && cd ..
      - name: Test
        run: ./loda test
