name: CD

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate Version
        id: generate-version
        run: echo "::set-output name=version::$(date +"%-Y.%-m.%-d")"
      - name: Create Release
        uses: actions/create-release@v1
        id: create-release
        with:
          draft: false
          prerelease: false
          release_name: v${{ steps.generate-version.outputs.version }}
          tag_name: v${{ steps.generate-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
    outputs:
      version: ${{ steps.generate-version.outputs.version }}
      upload_url: ${{ steps.create-release.outputs.upload_url }}
  build-linux:
    needs: create-release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cd src && make loda LODA_VERSION=${{ needs.create-release.outputs.version }}
      - name: Upload
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./loda
          asset_name: loda-linux
        env:
          GITHUB_TOKEN: ${{ github.token }}
  build-macos:
    needs: create-release
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cd src && make loda LODA_VERSION=${{ needs.create-release.outputs.version }}
      - name: Upload
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./loda
          asset_name: loda-macos
        env:
          GITHUB_TOKEN: ${{ github.token }}
  build-windows:
    needs: create-release
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: cd src && nmake.exe /F Makefile.windows loda LODA_VERSION=${{ needs.create-release.outputs.version }}
      - name: Upload
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./loda.exe
          asset_name: loda-windows.exe
        env:
          GITHUB_TOKEN: ${{ github.token }}
