name: Release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Generate Version
        id: generate-version
        run: echo "version=$(date +'%-y.%-m.%-d')" >> "$GITHUB_OUTPUT"
      - name: Create Release
        uses: actions/create-release@v1
        id: create-release
        with:
          draft: false
          prerelease: false
          release_name: v${{ steps.generate-version.outputs.version }}
          tag_name: v${{ steps.generate-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
    outputs:
      version: ${{ steps.generate-version.outputs.version }}
      upload_url: ${{ steps.create-release.outputs.upload_url }}
  build-windows:
    needs: create-release
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: cd src && nmake.exe /F Makefile.windows.mk loda LODA_PLATFORM=windows
      - name: Upload
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./loda.exe
          asset_name: loda-windows.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ github.token }}
