name: CD

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate Version
        id: generate-version
        run: echo "::set-output name=version::$(date +"%-Y.%-m.%-d")"
      - name: Create Release
        uses: actions/create-release@v1
        id: create-release
        with:
          draft: false
          prerelease: false
          release_name: v${{ steps.generate-version.outputs.version }}
          tag_name: v${{ steps.generate-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
    outputs:
      version: ${{ steps.generate-version.outputs.version }}
  build-linux:
    needs: create-release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cd src && make loda LODA_VERSION=${{ needs.create-release.outputs.version }}
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: loda-linux
          path: loda
  build-macos:
    needs: create-release
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cd src && make loda LODA_VERSION=${{ needs.create-release.outputs.version }}
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: loda-macos
          path: loda
  build-windows:
    needs: create-release
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: cd src && nmake.exe /F Makefile.windows loda LODA_VERSION=${{ needs.create-release.outputs.version }}
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: loda-windows
          path: loda.exe
