name: CD

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate Version
        run: echo "::set-output name=version::$(date +"%-Y.%-m.%-d")"
        id: version
      - name: Create Release
        uses: actions/create-release@v1
        id: create-release
        with:
          draft: false
          prerelease: false
          release_name: v${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
  build-linux:
    needs: release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: CheckVersion
        run: echo ${{ needs.release.outputs.version }}
      - name: Build
        run: cd src && make
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: loda-linux
          path: loda
  build-macos:
    needs: release
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: CheckVersion
        run: echo ${{ needs.release.outputs.version }}
      - name: Build
        run: cd src && make
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: loda-macos
          path: loda
  build-windows:
    needs: release
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: CheckVersion
        run: echo ${{ needs.release.outputs.version }}
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: cd src && nmake.exe /F Makefile.windows
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: loda-windows
          path: loda.exe
